# This is a basic workflow that is manually triggered

name: Clone to GHES

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      ghes_host:
        description: 'GHES Host'
        required: true
      ghes_token:
        description: 'GHES Token'
        required: true
      ghes_org:
        description: 'GHES Org Name'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  clone_to_ghes:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Checkout
      uses: actions/checkout@v3
    - name: Create and Clone Repo
      env:
        GH_HOST: ${{ github.event.inputs.ghes_host }}
        GH_ENTERPRISE_TOKEN: ${{ github.event.inputs.ghes_token }}
      run: gh repo create ${{ github.event.inputs.ghes_org }}/ghes-version-update --private --source=. --remote=upstream --push
